### ISSUE TITLE
Suggestions: RAPI command to set over-current threshold/timeout

### ISSUE THREAD

**Issue by jbakuwel** [OpenEVSE/ESP32_WiFi_V3.x#10]
As far as I understand a common problem in older Nissan Leafs is that the car charger's firmware might not be fully compliant with SAE J1772. Upgrading that firmware might pose challenges as I've discovered; there seems to be not much interest from dealers and it's also not a high priority for others offering services that dealers do not offer.

It would be great if OpenEVSE would have a RAPI command that changes the default overcurrent threshold and timeout.

#define OVERCURRENT_THRESHOLD 5 // A
​#define OVERCURRENT_TIMEOUT 5000UL // ms

**Comment by glynhudson** [comment]
This is an openevsse controller firmware issue which was fixed in V5.0.1 https://github.com/lincomatic/open_evse/issues/95.

Dee my reply https://github.com/lincomatic/open_evse/issues/105
