### ISSUE TITLE
Typo in Services/Solar PV divert information message

### ISSUE THREAD

**Issue by treepleks** [OpenEVSE/ESP32_WiFi_V3.x#105]
Charging will pause if the excess power drops below the nim charge rate for a period of time.
=>
Charging will pause if the excess power drops below the min charge rate for a period of time.

**Comment by glynhudson** [comment]
Where is this info message? Pease could you post a screenshot to illustrate

**Comment by treepleks** [comment]
[https://pasteboard.co/JlfMfHA.png](url)
