### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by jbakuwel** [OpenEVSE/ESP32_WiFi_V3.x#11]
"GUI documentation"

https://github.com/OpenEVSE/ESP32_WiFi_V3.x/blob/master/gui/readme.md

**Comment by jeremypoulter** [comment]
Interesting... thanks for highlighting this.

**Comment by glynhudson** [comment]
Where did you find this link? The correct link should be: https://github.com/OpenEVSE/openevse_wifi_gui/tree/master

**Comment by jbakuwel** [comment]
It's in this section: https://github.com/OpenEVSE/ESP32_WiFi_V3.x#building-the-gui

**Comment by jeremypoulter** [comment]
Fixed this locally, the problem was that `gui` is a submodule so if that is not checked out or (apparently) on GitHub this can not be followed. I have changed to a link to the GitHub repo rather than a relative link.
