### ISSUE TITLE
ESP32-Gateway Update

### ISSUE THREAD

**Issue by Pukkahq** [OpenEVSE/ESP32_WiFi_V3.x#113]
When trying to load the new firmware via a web browser and error occurs.
![image](https://user-images.githubusercontent.com/15746724/91744941-270b9d00-ebb2-11ea-92b6-6d340ed6a6bf.png)

I am not sure how to debug further.

**Comment by mikeh2010** [comment]
The only time I've seen this trying to update when behind my reverse proxy...

**Comment by glynhudson** [comment]
There must have been an issue with the proxy. Unable to replicate when updating via a normal connection.
