### ISSUE TITLE
Session Status does not reflect WiFi connectivity status

### ISSUE THREAD

**Issue by kkalganov** [OpenEVSE/ESP32_WiFi_V3.x#114]
Session Status seems to rely on the latest update from the device, even if such update was ages ago. If connection is lost (like unreliable WiFi) status should change to "Unknown".

**Comment by glynhudson** [comment]
If the connection to the unit is lost all the data on the interface could potentially be out of date, I don't think this is a big issue. Connection should not be lost of the unit has a decent WiFi signal strength.
