### ISSUE TITLE
Daylight Saving Time (DST) 

### ISSUE THREAD

**Issue by glynhudson** [OpenEVSE/ESP32_WiFi_V3.x#124]
DST needs to be implemented for regions that unfortunately needs to deal with DST. Could this be done automatically based on NTP country selection? Or maybe it's easier to implement with a simple check box for 'enable DST'?

**Comment by jeremypoulter** [comment]
It should be as far as I am aware... Although - it may not updated the EVSE, may just be the ESP...

**Comment by glynhudson** [comment]
Ah interesting, was DST implemented as part of NTP? I assumed the NTP will return unix time

**Comment by jeremypoulter** [comment]
Yeah, DST should have been built into the time zone selection, as in if you select Europe/London it should be also applying the DST hour so GMT+1

**Comment by jeremypoulter** [comment]
This looked to have worked ok for me, did you see any issues?

**Comment by glynhudson** [comment]
Yes, I can confirm DST is already implemented! It worked perfectly for me at the weekend. Nice work 👍
