### ISSUE TITLE
DEV V4.0: GUI does not change colour to indicate vehicle has been connected while in Sleeping state 

### ISSUE THREAD

**Issue by glynhudson** [OpenEVSE/ESP32_WiFi_V3.x#142]
Related to https://github.com/lincomatic/open_evse/issues/136 

Does this just require updating to V7.1.1 controller FW? It would be good to display on the web interface and on the status API to show if a vehicle is connected while sleeping.

**Comment by jeremypoulter** [comment]
Yeah, you need the latest dev firmware. The connected status is now in reported. Will update the GUI to show this as well. Also need to fix the LED to show the two different colours

**Comment by jeremypoulter** [comment]
Done

**Comment by glynhudson** [comment]
Awesome! Just tested working 👍
