### ISSUE TITLE
DEV V4.0 MQTT posting 

### ISSUE THREAD

**Issue by glynhudson** [OpenEVSE/ESP32_WiFi_V3.x#151]
Currently, in the latest dev version I've noticed some issues with MQTT 

The normal metrics e.g amp, temp etc are not being posted to MQTT. Onle a few new metrics are being posting e.g

![Screenshot from 2021-02-24 15-10-04](https://user-images.githubusercontent.com/758844/109021433-c9fd2980-76b2-11eb-8f20-9967f648a3ca.png)

**Comment by jeremypoulter** [comment]
No probs, can we separate this in to 3 tickets for each different issue?

**Comment by glynhudson** [comment]
Sure, good point

**Comment by jeremypoulter** [comment]
This is an issue with all the data not being 'collected' when not charging. I made an optimisation to not collect some stats when not charging (like amps) and the stats are only posted to MQTT/EmonCMS when all are collected. Should be an easy fix.

**Comment by glynhudson** [comment]
Great, it's working now. RAPI over MQTT is also working 👍
