### ISSUE TITLE
DEV V4.0 Emoncms posting 

### ISSUE THREAD

**Issue by glynhudson** [OpenEVSE/ESP32_WiFi_V3.x#154]
After updating from V3.x to V4.x via the web interface I had to disable then re-enable Emoncms to begin posting. Then it posted two messages before stopping and not posting anymore.

![Screenshot from 2021-02-24 15-15-46](https://user-images.githubusercontent.com/758844/109021879-324c0b00-76b3-11eb-88a4-a251b8787557.png)
![Screenshot from 2021-02-24 15-15-08](https://user-images.githubusercontent.com/758844/109021882-32e4a180-76b3-11eb-8891-2908d74f61b1.png)

**Comment by jeremypoulter** [comment]
Actually this is the same issue as #151 :(

**Comment by glynhudson** [comment]
Nice work, it's working now 👍
