### ISSUE TITLE
DEV V4.0 Temperature display on web interface 

### ISSUE THREAD

**Issue by glynhudson** [OpenEVSE/ESP32_WiFi_V3.x#156]
After updating to controller V7.1.2 the temperature is no longer displayed on the web interface 

![Screenshot 2021-02-25 02 34 30](https://user-images.githubusercontent.com/758844/109094524-02802000-7712-11eb-9fae-c02ad7d9dae1.png)

I think the issue is that temp1 is no longer available: 

![Screenshot 2021-02-25 02 35 10](https://user-images.githubusercontent.com/758844/109094569-1af03a80-7712-11eb-8bd0-96bcec72effc.png)

temp4 has also now appeared, I'm not sure where these temperatures are coming from! Presumably one is the LCD and the other is the WiFi module? Is this documented somewhere @chris1howell? Which temp sensor is the best and most consistent to use on the web interface? 

We can assume that users running V4 WiFi will be running controller V7.1.2 or above.

**Comment by jeremypoulter** [comment]
It is working for me :( Can you check you have the latest GUI? This should display the temp assigned to `temp`: 
![image](https://user-images.githubusercontent.com/6116992/109426084-8290d900-79e3-11eb-9ebc-027a645b6c3e.png)

This is the same as is displayed on the LCD and what will be used for temp throttling. It is selected from essentially the first temp sensor in the first, but we can change the priority if need be. `temp4` is the temp sensor on the WiFi module.

**Comment by glynhudson** [comment]
Updated to latest version, temp1 is shown on the web interface.
