### ISSUE TITLE
Github Actions not running?

### ISSUE THREAD

**Issue by glynhudson** [OpenEVSE/ESP32_WiFi_V3.x#157]
I've just tried to find the latest binary to test via github actions. However, the last time jeremypoulter/issue5 branch was built was 18 days ago. Should github actions run each time a commit is made? I can see the latest commit to the jeremypoulter/issue5 branch was 2 days ago. 

![Screenshot 2021-03-02 23 05 59](https://user-images.githubusercontent.com/758844/109727232-dcdc9600-7bab-11eb-8339-d2858f79af86.png)

**Comment by jeremypoulter** [comment]
Hum... not sure... @chris1howell have you made any changes?

**Comment by chris1howell** [comment]
I have not made any changes, was wondering the same thing.

**Comment by jeremypoulter** [comment]
Hum... that is really odd... Is working fine on master and also if manually triggered just not on the branch...

**Comment by jeremypoulter** [comment]
I think I have 'fixed' this, I removed all of the conditions so it runs the builds on all branches/PRs
