### ISSUE TITLE
DEV V4.0 After updating to latest version web interface won't load without incognito mode

### ISSUE THREAD

**Issue by glynhudson** [OpenEVSE/ESP32_WiFi_V3.x#159]
After updating to the latest version the web interface won't load unless I use my browsers incognito mode which implies this is some sort of cache issue. Maybe bumping the js version number is needed to force the browser to fetch the new version? 

![Screenshot 2021-03-03 23 49 29](https://user-images.githubusercontent.com/758844/109888855-314f4680-7c7c-11eb-9e57-eabf051f807d.png)

**Comment by jeremypoulter** [comment]
Can you share a screenshot with the network tab open in both working and failing cases? I have added caching support in v4 as it makes it a lot faster. Also holding shift+clicking the reload button will fix the issue

**Comment by glynhudson** [comment]
I'm not able to replicate this any more, presumably my browser has refreshed the cache.

**Comment by jeremypoulter** [comment]
Potentially can do ` location.reload(true);` after upgrade ([ref](https://stackoverflow.com/questions/5721704/window-location-reload-with-clear-cache))

**Comment by glynhudson** [comment]
After updating to the latest version I've not experienced this issue anymore. I'll close this for the moment
