### ISSUE TITLE
temp1 has moved to temp3

### ISSUE THREAD

**Issue by glynhudson** [OpenEVSE/ESP32_WiFi_V3.x#16]
The 'pilot' and 'temp' metrics posted to Emoncms / MQTT are incorrect on the ESP32. The values for these metrics shown on the webpage are correct. 

Temp1 should be the internal temperature sensor. Temp2/3 are not used on the standard OpenEVSE and should be large negative numbers. 

![Screenshot_2019-09-08_00-08-50](https://user-images.githubusercontent.com/758844/64481086-df377d00-d1cc-11e9-94a8-9501d9079892.png)

**Comment by jeremypoulter** [comment]
It was not even a temp, was the pilot ;-)
