### ISSUE TITLE
Current section under status page reports incorrect max current on L2. 

### ISSUE THREAD

**Issue by joshchernoff** [OpenEVSE/ESP32_WiFi_V3.x#161]
Expected: 
Given I'm on the `/#status` page
When I set the max current under the setup section to 40a
Then I expect the current section to reflect the 40a value set under the setup section. 

Observed: 
Given I'm on the `/#status` page
When I set the max current under the setup section to 40a
Then I see the current section always shows max at default 80a as seen below in the provided screen show. 

<img width="982" alt="OpenEVSE" src="https://user-images.githubusercontent.com/961877/110218348-44c20380-7e6e-11eb-8ff1-0446d2469098.png">

**Comment by glynhudson** [comment]
This is showing the max current that your unit is capable of. The hard limit is set in the firmware, the maximum hard current on your unit is set to 80A. The hard limit cannot be changed via the interface. You can set a soft current limit by adjusting the "Max Current". 

e.g the EU firmware is set to maximum 32A https://github.com/openenergymonitor/open_evse/blob/master/firmware/open_evse/open_evse.h#L427

**Comment by chris1howell** [comment]
SAE J1772 defines the Absolute minimum current as 6A and the Absolute
maximum of 80A. This is different than the pilot setting which is the
current reported to the Vehicle. The Absolute MIN and MAX can be changed in
the source code.

The latest OpenEVSE firmware (7.2.1) has a new command $SC xx M to change
the absolute Maximum from the SAE J1772 to another value, typically the
maximum limit of your hardware. Note for security this is a one time
setting written to EEPROM. The controller EEPROM will need to be fully
wiped and reprogrammed to remove the Limit.

**Comment by joshchernoff** [comment]
Closing as not a bug.

**Comment by joshchernoff** [comment]
Thanks for the update. It's a bummer the UI does not better convey that as it's easy to conflate the two at first glance.
