### ISSUE TITLE
Build fails - no OpenEVSE lib in lib/ folder

### ISSUE THREAD

**Issue by TheBluProject** [OpenEVSE/ESP32_WiFi_V3.x#163]
Hi,

At the moment git workflow checkouts the 'openevse_wifi_timer_apis' from jeremypoulter/OpenEVSE_Lib

In the master branch there's no lib in the lib/ folder

@jeremypoulter will you add this as submodule similarly to GUI or will it be a part of the master ?

**Comment by jeremypoulter** [comment]
That was just a shortcut for dev to stop me having to release a new version of the library every day. I will do a new OpenEVSE lib release and remove the checkout.

**Comment by jeremypoulter** [comment]
Done, fixed by 6b081606b3a7339276ea4e641c1d53e384f97ce2
