### ISSUE TITLE
Captive portal requires clicking on OpenEVES link

### ISSUE THREAD

**Issue by glynhudson** [OpenEVSE/ESP32_WiFi_V3.x#17]
The captive portal re-direct currently directs to a page with a link called "OpenEVES" which requires the user to click to forward to the actual landing page. 

![Screenshot_20190907-140217](https://user-images.githubusercontent.com/758844/64475442-d322cf80-d17a-11e9-85fa-a9d048209dd1.png)

**Comment by jeremypoulter** [comment]
Will be fixed by jeremypoulter/ArduinoMongoose#3

**Comment by glynhudson** [comment]
https://github.com/OpenEVSE/ESP32_WiFi_V3.x/blob/master/src/web_server.cpp#L944

**Comment by jeremypoulter** [comment]
Fixed with jeremypoulter/ArduinoMongoose#3

**Comment by glynhudson** [comment]
Confirmed fixed, nice work :+1:
