### ISSUE TITLE
Setting the time does not work

### ISSUE THREAD

**Issue by jeremypoulter** [OpenEVSE/ESP32_WiFi_V3.x#20]
Clicking the update time button sends the RAPI command but the connection is immediately closed.

**Comment by glynhudson** [comment]
Setting the time seems to work fine for me using Chrome

**Comment by glynhudson** [comment]
Seen updating I seem to be having issues setting the timer, see video: https://drive.google.com/file/d/13mJm9XhdJiivJOPdcbcGyOC0waMSQUp2/view

Are you able to replicate?

**Comment by jeremypoulter** [comment]
ArduinoMongoose library?

**Comment by glynhudson** [comment]
Do you mean I need to update the ArduinoMongoose library? Should this happen during the platformio compile process or is this a manual step?

**Comment by jeremypoulter** [comment]
May need to force it as it is not properly managed yet

**Comment by glynhudson** [comment]
No worries, I've done `pio lib install https://github.com/jeremypoulter/arduinoMongoose.git`. It seemed to pull in some new changes. Will report back once I've updated. I'm still having trouble with OTA so will need to open up the box to do a physical update. Thanks.

**Comment by jeremypoulter** [comment]
For OTA try
```
curl -F 'file=@.pio/build/openevse_huzzah32/firmware.bin'  http://172.16.0.157/update && echo
```
(obviously change the IP)

**Comment by glynhudson** [comment]
Fantastic! That worked, so much easier than a physical serial upload. Time setting is now working great with the latest mongoose lib 👍
