### ISSUE TITLE
Memory leak 

### ISSUE THREAD

**Issue by glynhudson** [OpenEVSE/ESP32_WiFi_V3.x#21]
The free heap seems to be reducing linearly! After being running for about 24hrs the unit required a rest to become responsive. Since then, I've setup better logging to capture the freeheap to see what value resulted in a crash. I will continue to monitor 

![Selection_240](https://user-images.githubusercontent.com/758844/64545020-f044d300-d31f-11e9-94bb-d6a2600c8c2c.jpg)

**Comment by glynhudson** [comment]
It's now been 6 days and the ESP32 is still up and running, the free heap seems to nosedive then recover on an almost periodic basis:

![Screenshot 2019-09-15 at 23 30 20](https://user-images.githubusercontent.com/758844/64928492-dc620b00-d810-11e9-9548-f927c8b70517.png)

As a comparison here is a graph of the freeheap of the ESP8266 version over a 7 day period:

![Screenshot 2019-09-15 at 23 31 59](https://user-images.githubusercontent.com/758844/64928510-18956b80-d811-11e9-83b2-0426a37f8bf4.png)

**Comment by glynhudson** [comment]
After the latest update (WiFi scan) the ESP32 has been very unstable, it only runs for 10hrs before hanging. A physical reset is then required to bring the module back to life. When the unit is in the hanging state everything including serial debug, MQTT, HTTP and Emoncms posting stops. 

This shows the graph of free heap, unlike previously the unit does not automatically reboot. I have been manually rebooting ever 24hrs or so. This is running on a Huzzah 32 

![Screenshot 2019-11-01 at 00 13 57](https://user-images.githubusercontent.com/758844/67994325-8f10f000-fc3c-11e9-8a2f-564f11c8fe89.png)

**Comment by CircuitSetup** [comment]
I was having a very similar problem with my version of EmonCMS, which was modified to use ESP32. I found the instability and freezing would happen more quickly when the GUI was left open. In my case the memory leak was caused by the async library not releasing sessions (espasyncwebserver, and AsyncTCP). I see that this is using a different library for the webserver, but it may be something to look into.

**Comment by glynhudson** [comment]
Switching off HTTP posting to Emoncms has made a significant differance. The unit has not frozen since and the free ram does not go down so low. However, it looks like the memory leak is still preset: 

![Emoncms - graph 233](https://user-images.githubusercontent.com/758844/68869482-27a17880-06f1-11ea-9970-4977c23808fb.png)

**Comment by glynhudson** [comment]
Fixed by https://github.com/OpenEVSE/ESP32_WiFi_V3.x/commit/451db125602c7b0b1cd3462400d9695190626848

![](https://lh3.googleusercontent.com/-FwkerKlDSoo/XeUR9pbx7pI/AAAAAAADOT4/xN8lOGNld5YAYq60zEVdUPsJCRZRYU1hwCK8BGAsYHg/s0/2019-12-02.jpg)
