### ISSUE TITLE
Update codacy badge

### ISSUE THREAD

**Issue by glynhudson** [OpenEVSE/ESP32_WiFi_V3.x#22]
Currently, the codacy badge in the readme still points at the ESP8266 version:
https://app.codacy.com/manual/jeremy_poulter/ESP8266_WiFi_v2.x/dashboard

**Comment by jeremypoulter** [comment]
I believe Codacy still needs to be enabled on the main repo(s) and I believe we were waiting for @chris1howell to do this.
