### ISSUE TITLE
Compile issues with newer SDK

### ISSUE THREAD

**Issue by jeremypoulter** [OpenEVSE/ESP32_WiFi_V3.x#23]
Building with 1.10.0 or the ESP32 BSP fails, see https://travis-ci.org/OpenEVSE/ESP32_WiFi_V3.x/builds/585990684

Most likely as a result of https://github.com/espressif/arduino-esp32/commit/56ce580

**Comment by glynhudson** [comment]
Fixed for the moment by forcing `platform_esp32 = espressif32@1.9.0`  https://github.com/OpenEVSE/ESP32_WiFi_V3.x/commit/4fa21739949a57373d2443326c7d31adea7954f9

**Comment by jeremypoulter** [comment]
Fixed
