### ISSUE TITLE
After changing MQTT sub-topic RAPI via MQTT does not respond until reboot

### ISSUE THREAD

**Issue by glynhudson** [OpenEVSE/ESP32_WiFi_V3.x#52]
After changing MQTT sub-topic RAPI via MQTT does not respond until reboot

e.g changing MQTT sub-topic from `openevse-xyz` to `emon/openevse` and posting to `emon/openevse/rapi/in/$GS` the openevse does not respond on `emon/openevse/rapi/out` until the ESP32 is rebooted.

**Comment by jeremypoulter** [comment]
Yes, probably need to reconnect to the MQTT server.

**Comment by jeremypoulter** [comment]
Needs this function implementing: https://github.com/OpenEVSE/ESP32_WiFi_V3.x/blob/master/src/mqtt.cpp#L241:L245
