### ISSUE TITLE
HTTP authentication doesnt work using IDF build

### ISSUE THREAD

**Issue by glynhudson** [OpenEVSE/ESP32_WiFi_V3.x#55]
Using `openevse_huzzah32_idf` environment build HTTP authentication doesn't prompt for username and password on page load. However, the username and password are correctly saved and show up on the interface.

**Comment by jeremypoulter** [comment]
I had a look at this and it is working fine for me. Can you ensure you have the latest ArduinoMongoose Library? Needs to be at least 0.0.8 for the web auth to work. It is probably worth looking to see if we can save the builds generated by Travis CI to ensure a clean build env.

**Comment by glynhudson** [comment]
Your're right, it works fine for me after a clean build. Sorry for the hassle.
