### ISSUE TITLE
Add supervised heartbeat support

### ISSUE THREAD

**Issue by gw8484** [OpenEVSE/ESP32_WiFi_V3.x#69]
OpeneEVSE Wifi access still stops after a while despite running the v3.0.4 with the improved Wifi connection handling which is better than previous version but still not reliable enough.  I see other people have reporting similar issues for a while and I understand improvements are being made.  However,  I have other devices on the same Wifi AP and they don't have such issues.   It's frustrating that OpenEVSE Wifi stops working up to a couple times a day for whatever reason and must be manually reset to recover.  I would like to suggest adding support for a supervised heartbeat mechanism that a supervisor client can activate with specified heartbeat interval via RAPI then OpenEVSE Wifi module must receive a heartbeat update via RAPI within a specified interval to continuing normal operation.  If heartbeats are not received for some specified time period then the OpenEVSE Wifi module would restart itself.   I believe such mechanism would provide a short term workaround to the Wifi problem while work can continue to find and fix the underlying causes over longer term.

**Comment by glynhudson** [comment]
WiFi module restarting has now been fixed
