### ISSUE TITLE
Charge Options

### ISSUE THREAD

**Issue by mikeh2010** [OpenEVSE/ESP32_WiFi_V3.x#73]
On main page - not able to use the Time Limit or Energy Limit select boxes.

![charge](https://user-images.githubusercontent.com/266618/80702321-ca4f8700-8ad8-11ea-8364-936bde5c71f6.gif)

**Comment by chris1howell** [comment]
This is a per session option, you must plug in a vehicle first. It is reset
when the vehicle is unplugged.

**Comment by mikeh2010** [comment]
OK cool. Thanks
