### ISSUE TITLE
Eco to Normal mode

### ISSUE THREAD

**Issue by Pukkahq** [OpenEVSE/ESP32_WiFi_V3.x#75]
No sure how to diagnose this. 

When in eco mode after a period of time (unknown at this time) charging goes back to normal mode

**Comment by jeremypoulter** [comment]
In the current `master` eco mode is turned off when the charging finishes. we currently have updates to the divert code that will enable 'eco' mode to be left on permanently, see the #54 / `divert_mode_off` branch

**Comment by Pukkahq** [comment]
The charging did not finish, the OpenEVSE webpage had gone back to normal mode. I have battery storage and this is filled before the car starts to charge, the blue circle is when i noticed it click a few buttons and restarted the ESP32.
I need some more sunny days in the UK to test further
![image](https://user-images.githubusercontent.com/15746724/80944104-ab0a6f80-8de0-11ea-8d65-3501e394825e.png)

**Comment by Pukkahq** [comment]
here is an overlay of our solar production
![image](https://user-images.githubusercontent.com/15746724/80944249-fcb2fa00-8de0-11ea-8a92-da81dac3e12f.png)

**Comment by Pukkahq** [comment]
Here is another screenshot, I am not sure what is going on but it is turning off eco mode

![image](https://user-images.githubusercontent.com/15746724/83405315-2cffaf80-a404-11ea-9e4f-c0d3a16dcfe3.png)

**Comment by jeremypoulter** [comment]
Is this with the master branch? If so there is an imminent update coming should improve matters.

**Comment by Pukkahq** [comment]
yes i am on the master branch. I would test one of the other branches but struggling with platformio

**Comment by jeremypoulter** [comment]
@Pukkahq we have merged the divert updates to master now, can you give them a go and let us know how it goes

**Comment by glynhudson** [comment]
@Pukkahq you can use the pre-compiled V3.2.0 beta release and update via the web interface to easily test the new version. See changelog and download release: https://github.com/OpenEVSE/ESP32_WiFi_V3.x/releases/tag/3.2.0

**Comment by Pukkahq** [comment]
I will report back soon, just installed it. need an empty car and sunny day now :)

**Comment by glynhudson** [comment]
3.2.0 issues being discussed in #90
