### ISSUE TITLE
Tesla Integration Issues 

### ISSUE THREAD

**Issue by glynhudson** [OpenEVSE/ESP32_WiFi_V3.x#80]
After testing https://github.com/OpenEVSE/ESP32_WiFi_V3.x/pull/67 for the past week or so I've noticed a view issues: 

1. JSON error on the `/status` output and some related Tesla API calls:

![Screenshot 2020-05-08 at 13 52 12](https://user-images.githubusercontent.com/758844/82239752-33d0f180-9931-11ea-9b9a-90d9734450f8.png)
![Screenshot 2020-05-11 at 16 04 35](https://user-images.githubusercontent.com/758844/82239753-34698800-9931-11ea-8fc3-ebe97bf140d3.png)
![Screenshot 2020-05-12 at 00 48 39](https://user-images.githubusercontent.com/758844/82239754-35021e80-9931-11ea-92db-d4de6e452c46.png)

**Update: status output JSON has been fixed by https://github.com/OpenEVSE/ESP32_WiFi_V3.x/commit/c3f36e984725ed9d82f8bc585b22f299a65a81a5**.  The other JSON issues remain, I wasn't sure how the nested JSON was supposed to work? 

2. No enabled / disabled status in `/config`, this will become an issue when we come to build the UI  for this feature?

3. Laggy UI, I've noticed when this feature is enabled the UI and RAPI calls can be unresponsive, requiring the interface to be reloaded to correctly display the EVSE status. More testing needed to figure out of this feature is the case of this. 

4. Token expiry? After about a week the Tesla info disappeared from `/status/ and `/config` displays `tesla_user: "",`, my Tesla login seems to have been forgotten. The serial debug periodically displays `requestAccessToken()`. Is it possible for the Tesla login expire? 

5. Often seeing `404 Not Found` errors with full server response via the serial debut  

```
getChargeState() vehidx=0
18-May-20, 19:12:00: Free memory 202052 - diff 42892 50584
resp
404 Not Found
_HEADER[Server]: nginx
_HEADER[Date]: Mon, 18 May 2020 18:12:01 GMT
_HEADER[Content-Type]: application/json; charset=utf-8
_HEADER[Content-Length]: 60
_HEADER[Connection]: keep-alive
_HEADER[X-Frame-Options]: SAMEORIGIN
_HEADER[X-XSS-Protection]: 1; mode=block
_HEADER[X-Content-Type-Options]: nosniff
_HEADER[Cache-Control]: no-cache
_HEADER[X-Request-Id]: aa3a486c28a9608e1907d4be2fb95526
_HEADER[X-Runtime]: 0.031904
{"response":null,"error":"not_found","error_description":""}
```
and if the car is sleeping I get the following error (accompanied by the full nginx response), waking the car up via the app and the errors goes away
```
408 Request Timeout
{"response":null,"error":"vehicle unavailable: {:error=>\"vehicle unavailable:\"}","error_description":""}
```

6. The Tesla config does not survive a module reboot. After the modules is restarted the config is lost, the config output shows `tesla_user: "",` . However, I can see via the serial debug output at startup that the config is being retrieved from the EEPROM but the `.com` of the email address username is missing the `m`

```
ot 'Europe/Lisbon|WET0WEST,M3.5.0/1,M10.5.0' 145 == 145 @ 652:80
Got 'xxxxxxx@gmail.c' 139 == 139 @ 832:32
Got '<TESLA-PASS>' 236 == 236 @ 864:32
```

Have you @chris1howell  or @lincomatic  experienced any of these issues?

**Comment by jeremypoulter** [comment]
I think I may have fixed the config related issues it the merge to the divert branch

**Comment by glynhudson** [comment]
Most of these issues have now been fixed, will open separate issue tickets from remaining issues
