### ISSUE TITLE
HTTP authentication doesn't work in captive portal / stand-alone mode.

### ISSUE THREAD

**Issue by DrFrankReade** [OpenEVSE/ESP32_WiFi_V3.x#87]
Running 3.2.0 dev
HTTP authentication only works when the ESP32 is connected to an AP. There is no security in captive portal / standalone mode. If WiFi fails, the system can't be secured. 

Danger scenario: I take my charger to an RV park and plug in overnight, and every kid in the place starts messing with my charger 

Wifi security isn't working either, but I have that in another issue.

**Comment by glynhudson** [comment]
AP mode uses a secure WiFi network so no need for HTTP authentication. HTTP authentication would interfere with captive portal.  

AP mode Wifi authentication is being discussed in #88. I will close this issue to avoid duplicate conversations.
