### ISSUE TITLE
Charging Stuck at 6A - firmware V3.2.1 beta 

### ISSUE THREAD

**Issue by Pukkahq** [OpenEVSE/ESP32_WiFi_V3.x#90]
I have just had our car plugged in with excess solar. the charge rate was stuck at 6A.
I cannot be certin what the charge rate was set to this morning when I disconnected the car. (does it go back to 32A like the old version?)

![image](https://user-images.githubusercontent.com/15746724/84771547-8d304d00-afd1-11ea-9545-7bef0e48d0e9.png)

![image](https://user-images.githubusercontent.com/15746724/84771670-bbae2800-afd1-11ea-9af5-f998d870c5f3.png)

**Comment by jeremypoulter** [comment]
With the divert mode off, what is the Max charge rate?

**Comment by Pukkahq** [comment]
When i toggled the button it was still 6A, I manually changed it to 32A and then turned eco mode back on

**Comment by Pukkahq** [comment]
Here is now, before i plugged the car

![image](https://user-images.githubusercontent.com/15746724/84897805-24fb6d00-b09e-11ea-9578-ea944b161893.png)

and once the car is plugged in
![image](https://user-images.githubusercontent.com/15746724/84897916-4d836700-b09e-11ea-8b5b-617b42456fcb.png)

**Comment by Pukkahq** [comment]
Changing the Max Current to 32A made no difference
![image](https://user-images.githubusercontent.com/15746724/84898234-d4384400-b09e-11ea-9831-03318ce0064d.png

Set the charger to normal and then change Max Current allowed it to go about 6a then back to eco and all is well

![image](https://user-images.githubusercontent.com/15746724/84898478-37c27180-b09f-11ea-874c-0eddecb33bca.png)

**Comment by jeremypoulter** [comment]
Would you be able to send us an export of the grid IE and voltage feeds? I am not quite sure what is going on.

**Comment by glynhudson** [comment]
> I cannot be certin what the charge rate was set to this morning when I disconnected the car. (does it go back to 32A like the old version?)

Ecomode is persistent in V3.2.0, so ecomode will stay enabled between charging sessions until it's disabled via the web interface. The timer can be used as a boost timer to charge the EV at full speed at an overnight off-peak time.

**Comment by Pukkahq** [comment]
same happened again today. only way to fix was normal mode adjust the Max Current and wait a few seconds for it to take affect. then go back to eco.

Also when in its broken state a reboot of the esp did not fix it.

**Comment by Pukkahq** [comment]
![image](https://user-images.githubusercontent.com/15746724/85289027-b009a800-b48e-11ea-9247-74bb81d182fc.png)

**Comment by glynhudson** [comment]
Is it possible to take a screencast video of the OpenEVSE interface to illustrate this issue. I'm struggling to re-create, the new solar PV divert seems to be working ok for me and does not seem to get stuck. It will be interesting to see how the figures change overtime which is not possible to see from a screenshot.

**Comment by Pukkahq** [comment]
Would you like access to the charger?

**Comment by glynhudson** [comment]
That would be great if you could arrange that. Please contact me privately support@openenergymonitor.zendesk.com

**Comment by glynhudson** [comment]
Here is a screencast video of @Pukkahq EVSE in action:

https://www.awesomescreenshot.com/video/275989?key=0532f3e2a01931c520bac3f85d58f3a0

I notice that when the EVSE was paused the excess feed was positive. The Grid IE is expecting positive import / negative export therefore the excess feed should be negative (exporting) when the EVSE is paused. 

Do you have any thoughts @jeremypoulter ?

**Comment by tentious** [comment]
I've also noticed the same here. Stuck at 6A.

![image](https://user-images.githubusercontent.com/1422016/88943685-67919700-d251-11ea-86cd-e7c8a7a35b64.png)

**Comment by Pukkahq** [comment]
I have just lost connection for a few min when it came back, the last update was 9 min ago.
![image](https://user-images.githubusercontent.com/15746724/89712642-13da2880-d98a-11ea-9f07-683465d046a8.png)

**Comment by Pukkahq** [comment]
Dont know if this is helpful.

![image](https://user-images.githubusercontent.com/15746724/89786395-c093e180-db13-11ea-8c55-438c5a79368e.png)

$GE^26
$OK 10 0001^20
$GG^24
$OK 9900 -1^3C
$GE^26
$OK 10 0001^20
$GG^24
$OK 9900 -1^3C
$SV 240760^06
$NK^21
$GE^26
$OK 10 0001^20
$GG^24
$OK 9900 -1^3C
$SV 242310^07
$NK^21
$GE^26
$OK 10 0001^20
$GG^24
$OK 9900 -1^3C
$GE^26
$OK 10 0001^20
$GG^24
$OK 9900 -1^3C
$GU^36
$OK 5066499 262383^1F
$GF^25
$OK 0 1 0^31
$GE^26
$OK 10 0001^20
$GS^30
$OK 03 2105 03 0540^27
$GG^24
$OK 10120 -1^0E
$GP^33
$OK 462 -2560 -2560^30
$GU^36
$OK 5094645 262383^11
$GF^25
$OK 0 1 0^31
$GE^26
$OK 10 0001^20
$GS^30
$OK 03 2117 03 0540^24
$GG^24
$OK 10120 -1^0E
$GP^33
$OK 462 -2560 -2560^30
$GU^36
$OK 5123243 262383^1E
$GF^25
$OK 0 1 0^31
$GE^26
$OK 10 0001^20

**Comment by Pukkahq** [comment]
$GG^24
$OK 9900 -1^3C
$SV 242140^00
$NK^21
$GP^33
$OK 462 -2560 -2560^30
$GE^26
$OK 10 0001^20
$GG^24
$OK 9900 -1^3C
$GE^26
$OK 10 0001^20
$GG^24
$OK 9900 -1^3C
$GE^26
$OK 10 0001^20
$GG^24
$OK 10120 -1^0E
$GU^36
$OK 5151979 262383^19
$GE^26
$OK 10 0001^20
$GG^24
$OK 10120 -1^0E
$GF^25
$OK 0 1 0^31
$GE^26
$OK 10 0001^20
$SV 240130^05
$NK^21
$GE^26
$OK 10 0001^20
$GG^24
$OK 10120 -1^0E
$SC 9 V^5B
$OK 9^39
$GS^30
$OK 03 2141 03 0540^27
$GE^26
$OK 9 0001^18
$GG^24
$OK 9240 -1^33
$GG^24
$OK 9240 -1^33
$SV 241710^00
$NK^21
$GE^26
$OK 9 0001^18
$GG^24
$OK 9240 -1^33
$SC 10 V^63
$OK 10^01
$GE^26
$OK 10 0001^20
$GG^24
$OK 9240 -1^33
$GP^33
$OK 462 -2560 -2560^30
$GE^26
$OK 10 0001^20
$GG^24
$OK 9020 -1^37
$GE^26
$OK 10 0001^20
$GG^24
$OK 9900 -1^3C
$GU^36
$OK 5179369 262383^18
$SV 242180^0C
$NK^21
$GE^26
$OK 10 0001^20
$GG^24
$OK 9900 -1^3C
$GF^25
$OK 0 1 0^31
$GE^26
$OK 10 0001^20
$GG^24
$OK 9900 -1^3C
$GE^26
$OK 10 0001^20
$GS^30
$OK 03 2153 03 0540^24
$SV 242700^02
$NK^21
$GE^26
$OK 10 0001^20
$GG^24
$OK 10120 -1^0E
$GE^26
$OK 10 0001^20
$GG^24
$OK 10120 -1^0E
$GE^26
$OK 10 0001^20
$GG^24
$OK 10120 -1^0E
$GG^24
$OK 10120 -1^0E
$GE^26
$OK 10 0001^20
$GG^24
$OK 10120 -1^0E
$GP^33
$OK 462 -2560 -2560^30
$SV 243110^04
$NK^21
$GU^36
$OK 5207747 262383^1A
$GE^26
$OK 10 0001^20
$GG^24
$OK 10120 -1^0E
$SC 8 V^5A
$OK 8^38
$GE^26
$OK 8 0001^19
$GG^24
$OK 10120 -1^0E
$GE^26
$OK 8 0001^19
$GG^24
$OK 10120 -1^0E
$SC 7 V^55
$OK 7^37
$GF^25
$OK 0 1 0^31

**Comment by glynhudson** [comment]
Other users have not reported this issue. Unable to replicate
