### ISSUE TITLE
MCP9808 Temperature Sensor 

### ISSUE THREAD

**Issue by chris1howell** [OpenEVSE/ESP32_WiFi_V3.x#92]
Add support for MCP9808 temperature sensor.

Development OpenEVSE WiFi integrated 5 - 12v switch mode power supply, two neoPixels and MCP9808 temperature sensor.

Code successfully tested on development hardware.

````
#include <Wire.h>
#include <Adafruit_MCP9808.h>

Adafruit_MCP9808 tempsensor = Adafruit_MCP9808();

void setup() {
  Wire.begin();
}

void loop() {
  float c = tempsensor.readTempC();
}
````

![2020-06-18](https://user-images.githubusercontent.com/758844/85077813-148ce480-b1bb-11ea-9e2b-4c472ec62337.jpg)

**Comment by jeremypoulter** [comment]
Should the temp just be exposed via MQTT/EmonCMS like the other temps, or are there additional requirements?

**Comment by glynhudson** [comment]
@chris1howell do we need a RAPI command to pass the temperature reading into the open_evse controller so it can be used for in the normal way for over temperature throttling etc.

**Comment by chris1howell** [comment]
It would probably be a good idea to pass the temp to the controller.

What I think we should do long term is have the controller only do the
safety shutdown at a single point 72C (or whatever we set) and have the
WiFi do the throttling.

The WiFi has a lot more resources to fine tune the current and will be
controlling for many other parameters.
